# Generated by Django 4.0 on 2022-01-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_askerprofile_age_remove_askerprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='askerprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='askerprofile',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
