# Generated by Django 4.0 on 2022-01-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_askerprofile_address_askerprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askerprofile',
            name='city',
            field=models.CharField(blank=True, default='sample city', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='askerprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('10', '10'), ('11', '11')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='askerprofile',
            name='school',
            field=models.CharField(blank=True, default='sample shool', max_length=50, null=True),
        ),
    ]
